### PR TITLE
Login

### LINKED ISSUE #4: Add Login Screen

### LINKED ISSUE #28: Implement Authorization Functionality
Needs to be implemented via Firebase Auth.

### LINKED ISSUE #31: Refactor current Provider usage to Riverpod

### PR DESCRIPTION
**Pull request by ExitTrance**

### CODE REVIEW

**Comment by keertirajmalik** [comment]
What do you use for development emulator or real-time device

**Comment by ExitTrance** [comment]
> What do you use for development emulator or real-time device?

At the moment I use both a real device (my Samsung S7 Edge), and an emulator that comes with Android Studio. Really depends on what I feel like that day, and if I'm doing anything besides working on this project, since the emulator kills my computer's performance. :)

**Comment by keertirajmalik** [comment]
Yeah been there but I was seeing a significant difference in how it was in the emulator and in my device.
So how do you overcome that issue? issue like font size etc.

**Comment by ExitTrance** [comment]
> was seeing a significant difference in how it was in the emulator and in my device.
Probably not just due to the screen size, but also due to pixel density, and system specific font size for example. Best to make it work on both.

> So how do you overcome that issue? an issue like font size etc.
For now, it works fine due to using objects with flex properties like Expanded. Padding doesn't cause much trouble, so I haven't paid much attention to it. 

As for font sizing (and also icon sizing), that's something I also struggle with to find a solution for without relying on packages. Too huge of  a system font setting, and it widgets start going out of bounds. I found some nice resources (linked down below) which might help you out. One is a general post about adaptive UIs in flutter, the others are interesting packages. If I find a better way, or find a custom solution, I'll let you know.

https://aloisdeniel.com/#/posts/adaptative-ui
https://pub.dev/packages/auto_size_text
https://pub.dev/packages/responsive_widgets

**Comment by keertirajmalik** [comment]
Thanks 😊

**Pull request merged**
